version: 2
defaults: &defaults
  working_directory: ~/terraform-ecs-plan-checker
  docker:
    - image: circleci/node:8.11.2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm publish
